services:
  # 🐘 PostgreSQL
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: servi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  # 🧱 NestJS backend (dev mode)
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: servi_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://admin:admin@postgres:5432/servi
      JWT_SECRET: somesecretservi
      JWT_EXPIRES_IN: 1d
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run start:dev
    networks:
      - backend_net

volumes:
  postgres_data:

networks:
  backend_net:
